AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: clean-arq-ref


Globals:
  Function:
    Timeout: 20

Resources:
  ObterUsuarios:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        Api:
          Type: Api
          Properties:
            Path: /usuario
            Method: get
    Metadata:
      DockerTag: java11-gradle-v1
      DockerContext: ./HelloWorldFunction
      Dockerfile: Dockerfile
