Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: com.lucasreis10.arq.ref.infrastructure.usuario.entrypoint.lambda.UsuarioLambda
      CodeUri: /home/lucas.reis/dev/github-pessoal/arq-ref
      Runtime: java11
      Architectures:
        - x86_64